baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[[params.ananke_socials]]
name = "github"
url = "https://github.com/cdfr232/ict302-3"
follow = true

[[params.ananke_socials]]
name = "reddit"
url = "https://www.reddit.com/"
follow = true

[taxonomies]
category = 'Names'
series = 'Britt'
tag = 'a'

[taxonomies]
category = 'Names'
series = 'Michael'
tag = 'b'

[taxonomies]
category = 'Names'
series = 'Chris'
tag = 'c'

[taxonomies]
category = 'Names'
series = 'Joe'
tag = 'd'
