baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Group 3 Wordpress Project Forum'
theme = 'ananke'

[params]
	AuthorName = 'Chris Frondal, Michael Kinser, Joseph Shodrowski, Britt Strong'
	Subtitle = 'This website is made in hugo and built to post and hold our weekly personal and group updates on the site development and class activities'

[[params.ananke_socials]]
name = "github"
url = "https://github.com/cdfr232/ict302-3"
follow = true

[[params.ananke_socials]]
name = "reddit"
url = "https://www.reddit.com/"
follow = true

